services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app

    env_file:
      - .env

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - database

  database:
    image: postgres:14-alpine
    env_file:
      - database.env