# Generated by Django 4.1.1 on 2022-11-16 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="user_profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        default="default.jpg",
                        upload_to="profile_images/",
                        verbose_name="Аватар",
                    ),
                ),
                (
                    "profile_type",
                    models.CharField(
                        choices=[("business", "Бизнес"), ("provider", "Провайдер")],
                        default="business",
                        max_length=8,
                        verbose_name="Тип профиля",
                    ),
                ),
                (
                    "premium",
                    models.BooleanField(default=False, verbose_name="Премиум-статус"),
                ),
            ],
            options={
                "verbose_name": "Профиль",
                "verbose_name_plural": "Профили",
            },
        ),
    ]
