# Generated by Django 4.1.1 on 2022-11-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adverts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advert",
            name="price",
            field=models.IntegerField(blank=True, default=0, verbose_name="Цена"),
        ),
    ]
