# Generated by Django 4.1.1 on 2022-12-21 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adverts", "0004_alter_advert_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="advert",
            options={"verbose_name": "Объявление", "verbose_name_plural": "Объявления"},
        ),
    ]
