# Generated by Django 4.1.1 on 2022-10-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=300, verbose_name="Название"
                    ),
                ),
                (
                    "slug",
                    models.CharField(blank=True, max_length=300, verbose_name="Слаг"),
                ),
                (
                    "intro",
                    models.CharField(
                        blank=True, max_length=600, verbose_name="Описание"
                    ),
                ),
                ("content", models.TextField(verbose_name="Содержание")),
                (
                    "post_type",
                    models.CharField(
                        choices=[
                            ("posts", "Блог"),
                            ("post", "Новость"),
                            ("event", "Событие"),
                        ],
                        default="posts",
                        max_length=5,
                        verbose_name="Тип записи",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(auto_now=True, verbose_name="Дата публикации"),
                ),
                ("published", models.BooleanField(default=True, verbose_name="Статус")),
            ],
            options={
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
            },
        ),
    ]
