# Generated by Django 4.1.1 on 2022-10-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_type",
            field=models.CharField(
                choices=[("blog", "Блог"), ("post", "Новость"), ("event", "Событие")],
                default="post",
                max_length=5,
                verbose_name="Тип записи",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="published",
            field=models.BooleanField(default=True, verbose_name="Статус публикации"),
        ),
    ]
